package rentivo_backend.controller;
import jakarta.validation.Valid; import org.springframework.web.bind.annotation.*; import rentivo_backend.dto.CategoryDtos.CategoryRequest; import rentivo_backend.dto.SubscriptionDtos.PlanRequest; import rentivo_backend.entity.*; import rentivo_backend.repository.*; import rentivo_backend.service.CategoryService; import java.math.BigDecimal; import java.util.*;
@RestController @RequestMapping("/api/admin") public class AdminController {private final UserRepository users;private final ListingRepository listings;private final CategoryRepository cats;private final SubscriptionPlanRepository plans;private final PaymentRepository payments;private final CategoryService catService; public AdminController(UserRepository u,ListingRepository l,CategoryRepository c,SubscriptionPlanRepository p,PaymentRepository pay,CategoryService cs){users=u;listings=l;cats=c;plans=p;payments=pay;catService=cs;}
 @GetMapping("/dashboard") public Map<String,Object> dashboard(){return Map.of("totalUsers",users.count(),"activeUsers",users.countByActiveTrue(),"totalListings",listings.count(),"pendingListings",listings.countByStatus(Listing.Status.PENDING),"approvedListings",listings.countByStatus(Listing.Status.APPROVED),"subscriptionPlans",plans.count(),"successfulPayments",payments.countByStatus("SUCCESS"),"revenue",Optional.ofNullable(payments.sumAmountByStatus("SUCCESS")).orElse(BigDecimal.ZERO));}
 @GetMapping("/users") public List<User> allUsers(){return users.findAll();}
 @PatchMapping("/users/{id}/active") public User activeUser(@PathVariable Long id,@RequestParam boolean value){User u=users.findById(id).orElseThrow(()->new IllegalArgumentException("User not found"));u.setActive(value);return users.save(u);}
 @GetMapping("/listings") public List<Listing> allListings(){return listings.findAll();}
 @PatchMapping("/listings/{id}/status") public Listing listingStatus(@PathVariable Long id,@RequestParam Listing.Status status){Listing l=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing not found"));l.setStatus(status);return listings.save(l);}
 @GetMapping("/categories") public List<Category> categories(){return cats.findAll();}
 @PostMapping("/categories") public Category createCategory(@Valid @RequestBody CategoryRequest r){return catService.save(r,null);}
 @PutMapping("/categories/{id}") public Category updateCategory(@PathVariable Long id,@Valid @RequestBody CategoryRequest r){return catService.save(r,id);}
 @PatchMapping("/categories/{id}/active") public void categoryActive(@PathVariable Long id,@RequestParam boolean value){catService.active(id,value);}
 @GetMapping("/subscriptions/plans") public List<SubscriptionPlan> plans(){return plans.findAll();}
 @PostMapping("/subscriptions/plans") public SubscriptionPlan createPlan(@Valid @RequestBody PlanRequest r){SubscriptionPlan p=new SubscriptionPlan();return savePlan(p,r);}
 @PutMapping("/subscriptions/plans/{id}") public SubscriptionPlan updatePlan(@PathVariable Long id,@Valid @RequestBody PlanRequest r){SubscriptionPlan p=plans.findById(id).orElseThrow(()->new IllegalArgumentException("Plan not found"));return savePlan(p,r);}
 @PatchMapping("/subscriptions/plans/{id}/active") public SubscriptionPlan planActive(@PathVariable Long id,@RequestParam boolean value){SubscriptionPlan p=plans.findById(id).orElseThrow(()->new IllegalArgumentException("Plan not found"));p.setActive(value);return plans.save(p);}
 private SubscriptionPlan savePlan(SubscriptionPlan p,PlanRequest r){p.setName(r.name());p.setPrice(r.price());p.setValidityDays(r.validityDays());p.setContactLimit(r.contactLimit());p.setDescription(r.description());if(r.active()!=null)p.setActive(r.active());return plans.save(p);}
}
