package rentivo_backend.service;
import jakarta.persistence.EntityNotFoundException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import rentivo_backend.dto.SubscriptionDtos.*; import rentivo_backend.entity.*; import rentivo_backend.repository.*; import java.time.LocalDateTime;
@Service public class SubscriptionService { private final UserRepository users;private final SubscriptionPlanRepository plans;private final UserSubscriptionRepository subs;private final ListingRepository listings;private final ContactAccessRepository accesses; public SubscriptionService(UserRepository u,SubscriptionPlanRepository p,UserSubscriptionRepository s,ListingRepository l,ContactAccessRepository a){users=u;plans=p;subs=s;listings=l;accesses=a;}
 public java.util.List<SubscriptionPlan> plans(){return plans.findByActiveTrueOrderByPriceAsc();}
 @Transactional public UserSubscription activate(Long uid,Long pid){User u=users.findById(uid).orElseThrow(()->new EntityNotFoundException("User not found"));SubscriptionPlan p=plans.findById(pid).orElseThrow(()->new EntityNotFoundException("Plan not found"));if(!p.isActive())throw new IllegalStateException("Plan inactive");UserSubscription s=new UserSubscription();s.setUser(u);s.setPlan(p);s.setStartAt(LocalDateTime.now());s.setEndAt(LocalDateTime.now().plusDays(p.getValidityDays()));s.setContactsUsed(0);s.setStatus(UserSubscription.Status.ACTIVE);return subs.save(s);}
 @Transactional public Status status(Long uid){var o=active(uid);if(o.isEmpty())return new Status(false,null,null,null,0,0,0,"No active subscription");var s=o.get();expire(s);if(s.getStatus()!=UserSubscription.Status.ACTIVE)return new Status(false,s.getPlan().getName(),s.getStartAt(),s.getEndAt(),s.getPlan().getContactLimit(),s.getContactsUsed(),0,"Subscription expired");int r=Math.max(0,s.getPlan().getContactLimit()-s.getContactsUsed());return new Status(true,s.getPlan().getName(),s.getStartAt(),s.getEndAt(),s.getPlan().getContactLimit(),s.getContactsUsed(),r,"Subscription active");}
 @Transactional public ContactResponse unlock(Long uid,Long lid){User u=users.findById(uid).orElseThrow(()->new EntityNotFoundException("User not found"));Listing l=listings.findById(lid).orElseThrow(()->new EntityNotFoundException("Listing not found"));if(l.getOwner().getId().equals(uid))throw new IllegalStateException("You cannot unlock your own contact");if(l.getStatus()!=Listing.Status.APPROVED)throw new IllegalStateException("Listing is not available");var existing=accesses.findByUserIdAndListingId(uid,lid);if(existing.isPresent()){var s=existing.get().getSubscription();int rem=Math.max(0,s.getPlan().getContactLimit()-s.getContactsUsed());return new ContactResponse(true,l.getOwner().getName(),l.getContactPhone(),s.getContactsUsed(),rem,"Already unlocked");}UserSubscription s=active(uid).orElseThrow(()->new IllegalStateException("Active subscription is required"));expire(s);if(s.getStatus()!=UserSubscription.Status.ACTIVE)throw new IllegalStateException("Subscription expired");if(s.getContactsUsed()>=s.getPlan().getContactLimit())throw new IllegalStateException("Contact limit reached");s.setContactsUsed(s.getContactsUsed()+1);subs.save(s);ContactAccess a=new ContactAccess();a.setUser(u);a.setListing(l);a.setSubscription(s);a.setUnlockedAt(LocalDateTime.now());accesses.save(a);return new ContactResponse(true,l.getOwner().getName(),l.getContactPhone(),s.getContactsUsed(),s.getPlan().getContactLimit()-s.getContactsUsed(),"Owner contact unlocked");}
 private java.util.Optional<UserSubscription> active(Long uid){return subs.findTopByUserIdAndStatusOrderByEndAtDesc(uid,UserSubscription.Status.ACTIVE);} private void expire(UserSubscription s){if(!s.getEndAt().isAfter(LocalDateTime.now())){s.setStatus(UserSubscription.Status.EXPIRED);subs.save(s);}}
}
